export const paisesComDdi = [
  { nome: "Afeganistão", ddi: "+93" },
  { nome: "África do Sul", ddi: "+27" },
  { nome: "Alemanha", ddi: "+49" },
  { nome: "Arábia Saudita", ddi: "+966" },
  { nome: "Argentina", ddi: "+54" },
  { nome: "Austrália", ddi: "+61" },
  { nome: "Brasil", ddi: "+55" },
  { nome: "Canadá", ddi: "+1" },
  { nome: "Chile", ddi: "+56" },
  { nome: "China", ddi: "+86" },
  { nome: "Coreia do Sul", ddi: "+82" },
  { nome: "Espanha", ddi: "+34" },
  { nome: "Estados Unidos", ddi: "+1" },
  { nome: "França", ddi: "+33" },
  { nome: "Índia", ddi: "+91" },
  { nome: "Itália", ddi: "+39" },
  { nome: "Japão", ddi: "+81" },
  { nome: "México", ddi: "+52" },
  { nome: "Portugal", ddi: "+351" },
  { nome: "Reino Unido", ddi: "+44" },
  { nome: "Rússia", ddi: "+7" },
  { nome: "Suécia", ddi: "+46" },
  { nome: "Suíça", ddi: "+41" },
  { nome: "Uruguai", ddi: "+598" },
  { nome: "Venezuela", ddi: "+58" },
];
